In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import cv2 as cv 
import glob
import torch
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler,Subset
from torchvision import transforms
from IPython.display import HTML
from torchvision import transforms
from sklearn.model_selection import train_test_split
from torchvision  import datasets 
from sklearn.model_selection import KFold
import optuna
from optuna.trial import Trial
from tqdm import tqdm
import torch.optim as optim
import torch.nn as nn
from torchvision import models
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from torch.utils.data import Subset, DataLoader

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [3]:
combined_data = "/kaggle/input/deepfake-and-real-images/Dataset/Test"

In [4]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize images to 224x224
    transforms.ToTensor(),         # Convert to Tensor
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])  # Normalize
])

In [5]:
combinedData = datasets.ImageFolder(combined_data, transform=transform)

In [6]:
combinedData

Dataset ImageFolder
    Number of datapoints: 10905
    Root location: /kaggle/input/deepfake-and-real-images/Dataset/Test
    StandardTransform
Transform: Compose(
               Resize(size=(224, 224), interpolation=bilinear, max_size=None, antialias=True)
               ToTensor()
               Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
           )

In [7]:
kf = KFold(n_splits=3, shuffle=True, random_state=42) 

In [8]:
samples = len(combinedData)
samples

10905

In [9]:
folds = list(kf.split(np.arange(samples)))

In [10]:
folds

[(array([    1,     2,     4, ..., 10900, 10901, 10902]),
  array([    0,     3,     8, ..., 10899, 10903, 10904])),
 (array([    0,     1,     3, ..., 10902, 10903, 10904]),
  array([    2,    15,    18, ..., 10889, 10900, 10901])),
 (array([    0,     2,     3, ..., 10901, 10903, 10904]),
  array([    1,     4,     5, ..., 10896, 10897, 10902]))]

# Split our data into 3 Kfolds

In [11]:
for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
    print(f"Fold {fold_idx + 1}")
    
    train_size = int(0.75* len(train_val_idx)) 
    val_size = len(train_val_idx) - train_size #25
    
    train_idx = train_val_idx[:train_size]
    val_idx = train_val_idx[train_size:]
    
    # Create subsets
    train_set = Subset(combinedData, train_idx)
    val_set = Subset(combinedData, val_idx)
    test_set = Subset(combinedData, test_idx)
    
    train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
    test_loader = DataLoader(test_set, batch_size=32, shuffle=False)
    
    print(f"Train size: {len(train_set)}")
    print(f"Validation size: {len(val_set)}")
    print(f"Test size: {len(test_set)}")

Fold 1
Train size: 5452
Validation size: 1818
Test size: 3635
Fold 2
Train size: 5452
Validation size: 1818
Test size: 3635
Fold 3
Train size: 5452
Validation size: 1818
Test size: 3635


# Define our model ResNet-50

In [12]:

def get_model(name):
    if name=="resnet-50":
        model= models.resnet50(pretrained=True)
        for param in model.parameters():
            param.requires_grad = False
    
        model.fc = nn.Linear(model.fc.in_features, 2)
    else:
        raise ValueError("Model name must be 'alexnet' or 'vgg16'")
    return model

In [ ]:
# Fine-tune


# def get_model(name):
#     if name == "resnet-50":
#         model = models.resnet50(pretrained=True)
        
#         # Freeze all layers initially
#         for param in model.parameters():
#             param.requires_grad = False
            
#         # Unfreeze the final two residual blocks (layer3 and layer4)
#         for layer in [model.layer3, model.layer4]:
#             for param in layer.parameters():
#                 param.requires_grad = True
                
#         # Unfreeze and modify the final fully connected layer
#         model.fc = nn.Linear(model.fc.in_features, 2)
        
#         # Print layer status
#         def count_trainable_params(model):
#             return sum(p.numel() for p in model.parameters() if p.requires_grad)
            
#         print(f"Total trainable parameters: {count_trainable_params(model):,}")
        
#     else:
#         raise ValueError("Model name must be 'resnet-50'")
    
#     return model

# Training function

In [13]:
def TrainingModels(model, train_loader, criterion, optimizer):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for images, labels in tqdm(train_loader, desc="Training", leave=False):
        images, labels = images.to(device), labels.to(device)
        
        outputs = model(images)
        loss = criterion(outputs, labels)  #loss function used to compute the error between predictions and true labels
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, preds = torch.max(outputs, 1) # max score from the scores of two classes
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc




In [55]:
# Fine-tune

# def TrainingModels(model, train_loader, criterion, optimizer):
#     model.train()
#     running_loss = 0.0
#     correct = 0
#     total = 0
    
#     # Add gradient clipping to prevent exploding gradients
#     max_grad_norm = 1.0
    
#     for images, labels in tqdm(train_loader, desc="Training", leave=False):
#         images, labels = images.to(device), labels.to(device)
        
#         outputs = model(images)
#         loss = criterion(outputs, labels)
        
#         optimizer.zero_grad()
#         loss.backward()
        
#         # Clip gradients
#         torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        
#         optimizer.step()

#         running_loss += loss.item() * images.size(0)
#         _, preds = torch.max(outputs, 1)
#         correct += (preds == labels).sum().item()
#         total += labels.size(0)

#     epoch_loss = running_loss / total
#     epoch_acc = correct / total
#     return epoch_loss, epoch_acc

# Eval function

In [14]:
def evaluate(model, data_loader, criterion):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in tqdm(data_loader, desc="Evaluating", leave=False):
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc

# Optimize the Learning rate using Optuna

In [15]:
def LR_optimization(trial: Trial):
    lr = trial.suggest_loguniform("lr", 1e-5, 1e-2)
    
    # Iterate over folds
    fold_results = []
    for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
        print(f"\nFold {fold_idx + 1}")
        
        train_size = int(0.75 * len(train_val_idx))
        train_idx = train_val_idx[:train_size]
        val_idx = train_val_idx[train_size:]

        train_set = Subset(combinedData, train_idx)
        val_set = Subset(combinedData, val_idx)
        test_set = Subset(combinedData, test_idx)

        train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
        val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
        test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

        
        for model_name in ["resnet-50"]:
            print(f"\nTraining model: {model_name.upper()} on Fold {fold_idx + 1}")
            
            # Initialize model
            model = get_model(model_name).to(device)
            criterion = nn.CrossEntropyLoss()
            optimizer = optim.Adam(model.parameters(), lr=lr)

            for epoch in range(5):
                current_lr = optimizer.param_groups[0]["lr"]
                print(f"\nEpoch {epoch + 1}/5 | Learning Rate: {current_lr:.6f}")
                
                # Train and evaluate
                train_loss, train_acc = TrainingModels(model, train_loader, criterion, optimizer)
                val_loss, val_acc = evaluate(model, val_loader, criterion)

                print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
                print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")
            
            _, val_acc = evaluate(model, val_loader, criterion)
            fold_results.append(val_acc) 

    mean_val_acc = sum(fold_results) / len(fold_results)
    return mean_val_acc



In [ ]:
# Fine-tune

# def LR_optimization(trial: Trial):
#     # Use a smaller learning rate range for fine-tuning
#     lr = trial.suggest_loguniform("lr", 1e-6, 1e-3)
    
#     # Rest of the function remains the same
#     fold_results = []
#     for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
#         print(f"\nFold {fold_idx + 1}")
        
#         train_size = int(0.75 * len(train_val_idx))
#         train_idx = train_val_idx[:train_size]
#         val_idx = train_val_idx[train_size:]

#         train_set = Subset(combinedData, train_idx)
#         val_set = Subset(combinedData, val_idx)
#         test_set = Subset(combinedData, test_idx)

#         train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
#         val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
#         test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

#         for model_name in ["resnet-50"]:
#             print(f"\nFine-tuning model: {model_name.upper()} on Fold {fold_idx + 1}")
            
#             model = get_model(model_name).to(device)
#             criterion = nn.CrossEntropyLoss()
            
#             # Use a smaller weight decay for fine-tuning
#             optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
            
#             # Add learning rate scheduler for fine-tuning
#             scheduler = optim.lr_scheduler.ReduceLROnPlateau(
#                 optimizer, mode='max', factor=0.5, patience=2, verbose=True
#             )

#             for epoch in range(5):
#                 current_lr = optimizer.param_groups[0]["lr"]
#                 print(f"\nEpoch {epoch + 1}/5 | Learning Rate: {current_lr:.6f}")
                
#                 train_loss, train_acc = TrainingModels(model, train_loader, criterion, optimizer)
#                 val_loss, val_acc = evaluate(model, val_loader, criterion)
                
#                 # Update learning rate based on validation accuracy
#                 scheduler.step(val_acc)

#                 print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
#                 print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")
            
#             _, val_acc = evaluate(model, val_loader, criterion)
#             fold_results.append(val_acc)

#     mean_val_acc = sum(fold_results) / len(fold_results)
#     return mean_val_acc

In [16]:
study = optuna.create_study(direction="maximize")
study.optimize(LR_optimization, n_trials=5)

best_trial = study.best_trial
print("\nBest Trial:")
print(f"  Value (Mean Validation Accuracy): {best_trial.value}")
print(f"  Params: {best_trial.params}")

[I 2024-12-24 21:53:13,775] A new study created in memory with name: no-name-f91a8fb1-0f80-4626-b5b3-a026a07f58d4
<ipython-input-15-e1e71bb4b32b>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  lr = trial.suggest_loguniform("lr", 1e-5, 1e-2)
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date wei


Fold 1

Training model: RESNET-50 on Fold 1


Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|██████████| 97.8M/97.8M [00:00<00:00, 171MB/s] 



Epoch 1/5 | Learning Rate: 0.000411


Train Loss: 0.5910, Train Acc: 0.6818
Val Loss: 0.7907, Val Acc: 0.4422

Epoch 2/5 | Learning Rate: 0.000411


Train Loss: 0.5310, Train Acc: 0.7269
Val Loss: 0.6973, Val Acc: 0.5704

Epoch 3/5 | Learning Rate: 0.000411


Train Loss: 0.5063, Train Acc: 0.7434
Val Loss: 0.6154, Val Acc: 0.6606

Epoch 4/5 | Learning Rate: 0.000411


Train Loss: 0.4910, Train Acc: 0.7542
Val Loss: 0.6297, Val Acc: 0.6496

Epoch 5/5 | Learning Rate: 0.000411


Train Loss: 0.4820, Train Acc: 0.7561
Val Loss: 0.6240, Val Acc: 0.6650



Fold 2

Training model: RESNET-50 on Fold 2

Epoch 1/5 | Learning Rate: 0.000411


Train Loss: 0.5760, Train Acc: 0.6933
Val Loss: 0.8842, Val Acc: 0.3454

Epoch 2/5 | Learning Rate: 0.000411


Train Loss: 0.5265, Train Acc: 0.7291
Val Loss: 0.6770, Val Acc: 0.5979

Epoch 3/5 | Learning Rate: 0.000411


Train Loss: 0.4995, Train Acc: 0.7559
Val Loss: 0.8290, Val Acc: 0.4571

Epoch 4/5 | Learning Rate: 0.000411


Train Loss: 0.4978, Train Acc: 0.7506
Val Loss: 1.0273, Val Acc: 0.3438

Epoch 5/5 | Learning Rate: 0.000411


Train Loss: 0.5017, Train Acc: 0.7487
Val Loss: 0.5615, Val Acc: 0.7123



Fold 3

Training model: RESNET-50 on Fold 3

Epoch 1/5 | Learning Rate: 0.000411


Train Loss: 0.6011, Train Acc: 0.6836
Val Loss: 1.0530, Val Acc: 0.1793

Epoch 2/5 | Learning Rate: 0.000411


Train Loss: 0.5289, Train Acc: 0.7344
Val Loss: 0.7705, Val Acc: 0.4917

Epoch 3/5 | Learning Rate: 0.000411


Train Loss: 0.5059, Train Acc: 0.7471
Val Loss: 0.8354, Val Acc: 0.4554

Epoch 4/5 | Learning Rate: 0.000411


Train Loss: 0.4950, Train Acc: 0.7539
Val Loss: 0.7207, Val Acc: 0.5594

Epoch 5/5 | Learning Rate: 0.000411


Train Loss: 0.4814, Train Acc: 0.7650
Val Loss: 0.8964, Val Acc: 0.4263


[I 2024-12-24 22:04:37,757] Trial 0 finished with value: 0.6012101210121013 and parameters: {'lr': 0.0004110881374048701}. Best is trial 0 with value: 0.6012101210121013.



Fold 1

Training model: RESNET-50 on Fold 1

Epoch 1/5 | Learning Rate: 0.000029


Train Loss: 0.6334, Train Acc: 0.6634
Val Loss: 1.1082, Val Acc: 0.0198

Epoch 2/5 | Learning Rate: 0.000029


Train Loss: 0.6115, Train Acc: 0.6669
Val Loss: 0.9804, Val Acc: 0.0913

Epoch 3/5 | Learning Rate: 0.000029


Train Loss: 0.5951, Train Acc: 0.6759
Val Loss: 0.9876, Val Acc: 0.1089

Epoch 4/5 | Learning Rate: 0.000029


Train Loss: 0.5826, Train Acc: 0.6853
Val Loss: 1.0580, Val Acc: 0.1034

Epoch 5/5 | Learning Rate: 0.000029


Train Loss: 0.5736, Train Acc: 0.6867
Val Loss: 0.9029, Val Acc: 0.2294



Fold 2

Training model: RESNET-50 on Fold 2

Epoch 1/5 | Learning Rate: 0.000029


Train Loss: 0.6282, Train Acc: 0.6682
Val Loss: 1.0085, Val Acc: 0.0341

Epoch 2/5 | Learning Rate: 0.000029


Train Loss: 0.6050, Train Acc: 0.6744
Val Loss: 1.0203, Val Acc: 0.0490

Epoch 3/5 | Learning Rate: 0.000029


Train Loss: 0.5893, Train Acc: 0.6812
Val Loss: 1.0050, Val Acc: 0.0759

Epoch 4/5 | Learning Rate: 0.000029


Train Loss: 0.5780, Train Acc: 0.6878
Val Loss: 1.0342, Val Acc: 0.0787

Epoch 5/5 | Learning Rate: 0.000029


Train Loss: 0.5676, Train Acc: 0.6922
Val Loss: 0.9908, Val Acc: 0.1337



Fold 3

Training model: RESNET-50 on Fold 3

Epoch 1/5 | Learning Rate: 0.000029


Train Loss: 0.6286, Train Acc: 0.6783
Val Loss: 1.0770, Val Acc: 0.0083

Epoch 2/5 | Learning Rate: 0.000029


Train Loss: 0.6050, Train Acc: 0.6820
Val Loss: 1.0614, Val Acc: 0.0231

Epoch 3/5 | Learning Rate: 0.000029


Train Loss: 0.5906, Train Acc: 0.6875
Val Loss: 1.0280, Val Acc: 0.0572

Epoch 4/5 | Learning Rate: 0.000029


Train Loss: 0.5789, Train Acc: 0.6895
Val Loss: 0.9301, Val Acc: 0.1689

Epoch 5/5 | Learning Rate: 0.000029


Train Loss: 0.5674, Train Acc: 0.6996
Val Loss: 1.0473, Val Acc: 0.1078


[I 2024-12-24 22:15:43,467] Trial 1 finished with value: 0.15694902823615695 and parameters: {'lr': 2.8607540197238906e-05}. Best is trial 0 with value: 0.6012101210121013.



Fold 1

Training model: RESNET-50 on Fold 1

Epoch 1/5 | Learning Rate: 0.000617


Train Loss: 0.5733, Train Acc: 0.6939
Val Loss: 0.6191, Val Acc: 0.6502

Epoch 2/5 | Learning Rate: 0.000617


Train Loss: 0.5114, Train Acc: 0.7362
Val Loss: 1.0058, Val Acc: 0.3388

Epoch 3/5 | Learning Rate: 0.000617


Train Loss: 0.4961, Train Acc: 0.7458
Val Loss: 0.6349, Val Acc: 0.6485

Epoch 4/5 | Learning Rate: 0.000617


Train Loss: 0.4854, Train Acc: 0.7566
Val Loss: 0.4008, Val Acc: 0.8416

Epoch 5/5 | Learning Rate: 0.000617


Train Loss: 0.4822, Train Acc: 0.7630
Val Loss: 0.4405, Val Acc: 0.8009



Fold 2

Training model: RESNET-50 on Fold 2

Epoch 1/5 | Learning Rate: 0.000617


Train Loss: 0.5677, Train Acc: 0.6955
Val Loss: 1.2258, Val Acc: 0.1540

Epoch 2/5 | Learning Rate: 0.000617


Train Loss: 0.5214, Train Acc: 0.7324
Val Loss: 1.1315, Val Acc: 0.2574

Epoch 3/5 | Learning Rate: 0.000617


Train Loss: 0.5158, Train Acc: 0.7401
Val Loss: 1.0095, Val Acc: 0.3658

Epoch 4/5 | Learning Rate: 0.000617


Train Loss: 0.4833, Train Acc: 0.7557
Val Loss: 0.7161, Val Acc: 0.5787

Epoch 5/5 | Learning Rate: 0.000617


Train Loss: 0.4749, Train Acc: 0.7704
Val Loss: 0.7430, Val Acc: 0.5627



Fold 3

Training model: RESNET-50 on Fold 3

Epoch 1/5 | Learning Rate: 0.000617


Train Loss: 0.5669, Train Acc: 0.7040
Val Loss: 1.1000, Val Acc: 0.2057

Epoch 2/5 | Learning Rate: 0.000617


Train Loss: 0.5108, Train Acc: 0.7379
Val Loss: 0.9890, Val Acc: 0.3432

Epoch 3/5 | Learning Rate: 0.000617


Train Loss: 0.4955, Train Acc: 0.7557
Val Loss: 0.6705, Val Acc: 0.6161

Epoch 4/5 | Learning Rate: 0.000617


Train Loss: 0.4813, Train Acc: 0.7579
Val Loss: 0.6168, Val Acc: 0.6584

Epoch 5/5 | Learning Rate: 0.000617


Train Loss: 0.4819, Train Acc: 0.7639
Val Loss: 0.7768, Val Acc: 0.5314


[I 2024-12-24 22:26:48,382] Trial 2 finished with value: 0.6316464979831315 and parameters: {'lr': 0.0006172423196498955}. Best is trial 2 with value: 0.6316464979831315.



Fold 1

Training model: RESNET-50 on Fold 1

Epoch 1/5 | Learning Rate: 0.007583


Train Loss: 0.7892, Train Acc: 0.6783
Val Loss: 1.0187, Val Acc: 0.5110

Epoch 2/5 | Learning Rate: 0.007583


Train Loss: 0.6192, Train Acc: 0.7249
Val Loss: 0.1525, Val Acc: 0.9499

Epoch 3/5 | Learning Rate: 0.007583


Train Loss: 0.6500, Train Acc: 0.7238
Val Loss: 2.2178, Val Acc: 0.1969

Epoch 4/5 | Learning Rate: 0.007583


Train Loss: 0.5727, Train Acc: 0.7458
Val Loss: 2.7851, Val Acc: 0.1243

Epoch 5/5 | Learning Rate: 0.007583


Train Loss: 0.6781, Train Acc: 0.7309
Val Loss: 0.9078, Val Acc: 0.5875



Fold 2

Training model: RESNET-50 on Fold 2

Epoch 1/5 | Learning Rate: 0.007583


Train Loss: 0.8033, Train Acc: 0.6601
Val Loss: 1.5024, Val Acc: 0.3086

Epoch 2/5 | Learning Rate: 0.007583


Train Loss: 0.6706, Train Acc: 0.7205
Val Loss: 1.1295, Val Acc: 0.4510

Epoch 3/5 | Learning Rate: 0.007583


Train Loss: 0.5927, Train Acc: 0.7346
Val Loss: 1.9362, Val Acc: 0.2497

Epoch 4/5 | Learning Rate: 0.007583


Train Loss: 0.7318, Train Acc: 0.7144
Val Loss: 0.3850, Val Acc: 0.8306

Epoch 5/5 | Learning Rate: 0.007583


Train Loss: 0.5397, Train Acc: 0.7557
Val Loss: 0.8029, Val Acc: 0.6133



Fold 3

Training model: RESNET-50 on Fold 3

Epoch 1/5 | Learning Rate: 0.007583


Train Loss: 0.7303, Train Acc: 0.6908
Val Loss: 0.7772, Val Acc: 0.5858

Epoch 2/5 | Learning Rate: 0.007583


Train Loss: 0.6764, Train Acc: 0.7117
Val Loss: 0.7919, Val Acc: 0.6029

Epoch 3/5 | Learning Rate: 0.007583


Train Loss: 0.5970, Train Acc: 0.7339
Val Loss: 0.0767, Val Acc: 0.9846

Epoch 4/5 | Learning Rate: 0.007583


Train Loss: 0.8082, Train Acc: 0.7117
Val Loss: 2.0871, Val Acc: 0.2382

Epoch 5/5 | Learning Rate: 0.007583


Train Loss: 0.6328, Train Acc: 0.7381
Val Loss: 1.1365, Val Acc: 0.4802


[I 2024-12-24 22:38:00,357] Trial 3 finished with value: 0.5603226989365603 and parameters: {'lr': 0.007583275719997377}. Best is trial 2 with value: 0.6316464979831315.



Fold 1

Training model: RESNET-50 on Fold 1

Epoch 1/5 | Learning Rate: 0.000436


Train Loss: 0.5849, Train Acc: 0.6895
Val Loss: 0.7969, Val Acc: 0.4417

Epoch 2/5 | Learning Rate: 0.000436


Train Loss: 0.5232, Train Acc: 0.7269
Val Loss: 0.7468, Val Acc: 0.5330

Epoch 3/5 | Learning Rate: 0.000436


Train Loss: 0.5042, Train Acc: 0.7425
Val Loss: 0.7173, Val Acc: 0.5754

Epoch 4/5 | Learning Rate: 0.000436


Train Loss: 0.4905, Train Acc: 0.7555
Val Loss: 0.7235, Val Acc: 0.5748

Epoch 5/5 | Learning Rate: 0.000436


Train Loss: 0.4860, Train Acc: 0.7573
Val Loss: 1.1640, Val Acc: 0.2937



Fold 2

Training model: RESNET-50 on Fold 2

Epoch 1/5 | Learning Rate: 0.000436


Train Loss: 0.5793, Train Acc: 0.6983
Val Loss: 0.9567, Val Acc: 0.2679

Epoch 2/5 | Learning Rate: 0.000436


Train Loss: 0.5186, Train Acc: 0.7322
Val Loss: 0.8032, Val Acc: 0.4697

Epoch 3/5 | Learning Rate: 0.000436


Train Loss: 0.4981, Train Acc: 0.7522
Val Loss: 0.8663, Val Acc: 0.4411

Epoch 4/5 | Learning Rate: 0.000436


Train Loss: 0.4916, Train Acc: 0.7597
Val Loss: 0.4949, Val Acc: 0.7651

Epoch 5/5 | Learning Rate: 0.000436


Train Loss: 0.4837, Train Acc: 0.7595
Val Loss: 0.9459, Val Acc: 0.4092



Fold 3

Training model: RESNET-50 on Fold 3

Epoch 1/5 | Learning Rate: 0.000436


Train Loss: 0.5804, Train Acc: 0.6950
Val Loss: 1.3361, Val Acc: 0.0820

Epoch 2/5 | Learning Rate: 0.000436


Train Loss: 0.5224, Train Acc: 0.7346
Val Loss: 1.1435, Val Acc: 0.2068

Epoch 3/5 | Learning Rate: 0.000436


Train Loss: 0.4985, Train Acc: 0.7515
Val Loss: 0.8834, Val Acc: 0.4197

Epoch 4/5 | Learning Rate: 0.000436


Train Loss: 0.4885, Train Acc: 0.7537
Val Loss: 0.7363, Val Acc: 0.5528

Epoch 5/5 | Learning Rate: 0.000436


Train Loss: 0.4864, Train Acc: 0.7544
Val Loss: 0.6578, Val Acc: 0.6342


[I 2024-12-24 22:49:07,476] Trial 4 finished with value: 0.4457279061239457 and parameters: {'lr': 0.00043648808303298333}. Best is trial 2 with value: 0.6316464979831315.



Best Trial:
  Value (Mean Validation Accuracy): 0.6316464979831315
  Params: {'lr': 0.0006172423196498955}


# After the Optuna optimization process, we will use the best trial to set the learning rate

In [18]:
# Best learning rate from Optuna
best_lr = 0.0006172423196498955

In [19]:
final_results = {}

for model_name in ["resnet-50"]:
    print(f"\nTraining model: {model_name.upper()} with best learning rate {best_lr}")
    
    # Initialize model
    model = get_model(model_name).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=best_lr)
    
    # Create DataLoaders (assuming combinedData is split into train and test datasets)
    train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

    # Train the model
    for epoch in range(10):  # Example: 10 epochs
        print(f"\nEpoch {epoch + 1}/10")
        
        # Train and evaluate
        train_loss, train_acc = TrainingModels(model, train_loader, criterion, optimizer)
        print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
    
    # Final evaluation on the test set
    test_loss, test_acc = evaluate(model, test_loader, criterion)
    print(f"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.4f}")
    
    # Store results
    final_results[model_name] = {
        "Test Loss": test_loss,
        "Test Accuracy": test_acc
    }

# Print final results
print("\nFinal Results:")
for model_name, metrics in final_results.items():
    print(f"{model_name.upper()}:")
    for metric, value in metrics.items():
        print(f"  {metric}: {value:.4f}")


Training model: RESNET-50 with best learning rate 0.0006172423196498955

Epoch 1/10


Train Loss: 0.5776, Train Acc: 0.7041

Epoch 2/10


Train Loss: 0.5123, Train Acc: 0.7427

Epoch 3/10


Train Loss: 0.5019, Train Acc: 0.7449

Epoch 4/10


Train Loss: 0.4985, Train Acc: 0.7504

Epoch 5/10


Train Loss: 0.4790, Train Acc: 0.7590

Epoch 6/10


Train Loss: 0.4665, Train Acc: 0.7678

Epoch 7/10


Train Loss: 0.4753, Train Acc: 0.7625

Epoch 8/10


Train Loss: 0.4749, Train Acc: 0.7639

Epoch 9/10


Train Loss: 0.4656, Train Acc: 0.7781

Epoch 10/10


Train Loss: 0.4587, Train Acc: 0.7735


Test Loss: 0.5158, Test Acc: 0.7376

Final Results:
RESNET-50:
  Test Loss: 0.5158
  Test Accuracy: 0.7376


In [20]:
# Function to evaluate the model and get performance metrics
def evaluate_model(model, dataloader):
    model.eval()
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            
            outputs = model(inputs)
            _, predicted = torch.max(outputs, 1)
            
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return np.array(all_preds), np.array(all_labels)

# Initialize cross-validation metrics storage
confusion_matrices = []
accuracies = []
precisions = []
recalls = []
f1_scores = []

best_lr = 0.0006172423196498955

for model_name in ["resnet-50"]:
    print(f"\nTraining model: {model_name.upper()} with best learning rate {best_lr}")
    
    for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
        print(f"Fold {fold_idx + 1}")

        train_size = int(0.75 * len(train_val_idx))
        train_idx = train_val_idx[:train_size]
        val_idx = train_val_idx[train_size:]

        train_set = Subset(combinedData, train_idx)
        val_set = Subset(combinedData, val_idx)
        test_set = Subset(combinedData, test_idx)

        train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
        val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
        test_loader = DataLoader(test_set, batch_size=32, shuffle=False)
        
        
        model = get_model(model_name).to(device)
        optimizer = optim.Adam(model.parameters(), lr=best_lr)
        criterion = nn.CrossEntropyLoss()

        # Train the model
        for epoch in range(10):
            model.train()
            running_loss = 0.0
            for inputs, labels in train_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()
                running_loss += loss.item()

            print(f"Epoch {epoch+1}/10, Loss: {running_loss / len(train_loader):.4f}")

    
        preds, labels = evaluate_model(model, test_loader)

        
        accuracy = accuracy_score(labels, preds)
        precision = precision_score(labels, preds, average='weighted', zero_division=0)
        recall = recall_score(labels, preds, average='weighted', zero_division=0)
        f1 = f1_score(labels, preds, average='weighted', zero_division=0)
        cm = confusion_matrix(labels, preds)

        # Store metrics for the fold
        confusion_matrices.append(cm)
        accuracies.append(accuracy)
        precisions.append(precision)
        recalls.append(recall)
        f1_scores.append(f1)

        print(f"Fold {fold_idx + 1} - Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-Score: {f1:.4f}")
        print(f"Confusion Matrix:\n{cm}\n")

    # Average metrics across folds
    avg_accuracy = np.mean(accuracies)
    avg_precision = np.mean(precisions)
    avg_recall = np.mean(recalls)
    avg_f1_score = np.mean(f1_scores)
    avg_confusion_matrix = np.mean(confusion_matrices, axis=0)

    # Print final average metrics for the model
    print(f"\nFinal Results for {model_name.upper()}:")
    print(f"Average Accuracy: {avg_accuracy:.4f}")
    print(f"Average Precision: {avg_precision:.4f}")
    print(f"Average Recall: {avg_recall:.4f}")
    print(f"Average F1-Score: {avg_f1_score:.4f}")
    print(f"Average Confusion Matrix:\n{avg_confusion_matrix}")


Training model: RESNET-50 with best learning rate 0.0006172423196498955
Fold 1
Epoch 1/10, Loss: 0.5909
Epoch 2/10, Loss: 0.5197
Epoch 3/10, Loss: 0.4995
Epoch 4/10, Loss: 0.4874
Epoch 5/10, Loss: 0.4794
Epoch 6/10, Loss: 0.4684
Epoch 7/10, Loss: 0.4716
Epoch 8/10, Loss: 0.4683
Epoch 9/10, Loss: 0.4607
Epoch 10/10, Loss: 0.4483
Fold 1 - Accuracy: 0.7243, Precision: 0.7252, Recall: 0.7243, F1-Score: 0.7236
Confusion Matrix:
[[1436  428]
 [ 574 1197]]

Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Epoch 1/10, Loss: 0.5787
Epoch 2/10, Loss: 0.5188
Epoch 3/10, Loss: 0.5018
Epoch 4/10, Loss: 0.4925
Epoch 5/10, Loss: 0.4815
Epoch 6/10, Loss: 0.4688
Epoch 7/10, Loss: 0.4737
Epoch 8/10, Loss: 0.4735
Epoch 9/10, Loss: 0.4599
Epoch 10/10, Loss: 0.4647
Fold 2 - Accuracy: 0.7175, Precision: 0.7313, Recall: 0.7175, F1-Score: 0.7127
Confusion Matrix:
[[1547  287]
 [ 740 1061]]

Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Epoch 1/10, Loss: 0.5683
Epoch 2/10, Loss: 0.5226
Epoch 3/10, Loss: 0.4967
Epoch 4/10, Loss: 0.4887
Epoch 5/10, Loss: 0.4827
Epoch 6/10, Loss: 0.4797
Epoch 7/10, Loss: 0.4731
Epoch 8/10, Loss: 0.4718
Epoch 9/10, Loss: 0.4628
Epoch 10/10, Loss: 0.4609
Fold 3 - Accuracy: 0.7260, Precision: 0.7381, Recall: 0.7260, F1-Score: 0.7231
Confusion Matrix:
[[1495  299]
 [ 697 1144]]


Final Results for RESNET-50:
Average Accuracy: 0.7226
Average Precision: 0.7315
Average Recall: 0.7226
Average F1-Score: 0.7198
Average Confusion Matrix:
[[1492.66666667  338.        ]
 [ 670.33333333 1134.        ]]
