In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import cv2 as cv 
import glob
import torch
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler,Subset
from torchvision import transforms
from IPython.display import HTML
from torchvision import transforms
from sklearn.model_selection import train_test_split
from torchvision  import datasets 
from sklearn.model_selection import KFold
import optuna
from optuna.trial import Trial
from tqdm import tqdm
import torch.optim as optim
import torch.nn as nn
from torchvision import models
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from torch.utils.data import Subset, DataLoader

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [3]:
combined_data = "/kaggle/input/deepfake-and-real-images/Dataset/Test"

In [4]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize images to 224x224
    transforms.ToTensor(),         # Convert to Tensor
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])  # Normalize
])

In [5]:
combinedData = datasets.ImageFolder(combined_data, transform=transform)

In [6]:
combinedData

Dataset ImageFolder
    Number of datapoints: 10905
    Root location: /kaggle/input/deepfake-and-real-images/Dataset/Test
    StandardTransform
Transform: Compose(
               Resize(size=(224, 224), interpolation=bilinear, max_size=None, antialias=True)
               ToTensor()
               Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
           )

In [7]:
kf = KFold(n_splits=3, shuffle=True, random_state=42) 

In [8]:
samples = len(combinedData)
samples

10905

In [9]:
folds = list(kf.split(np.arange(samples)))

In [10]:
folds

[(array([    1,     2,     4, ..., 10900, 10901, 10902]),
  array([    0,     3,     8, ..., 10899, 10903, 10904])),
 (array([    0,     1,     3, ..., 10902, 10903, 10904]),
  array([    2,    15,    18, ..., 10889, 10900, 10901])),
 (array([    0,     2,     3, ..., 10901, 10903, 10904]),
  array([    1,     4,     5, ..., 10896, 10897, 10902]))]

# Split our data into 3 Kfolds

In [11]:
for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
    print(f"Fold {fold_idx + 1}")
    
    train_size = int(0.75* len(train_val_idx)) 
    val_size = len(train_val_idx) - train_size #25
    
    train_idx = train_val_idx[:train_size]
    val_idx = train_val_idx[train_size:]
    
    # Create subsets
    train_set = Subset(combinedData, train_idx)
    val_set = Subset(combinedData, val_idx)
    test_set = Subset(combinedData, test_idx)
    
    train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
    test_loader = DataLoader(test_set, batch_size=32, shuffle=False)
    
    print(f"Train size: {len(train_set)}")
    print(f"Validation size: {len(val_set)}")
    print(f"Test size: {len(test_set)}")

Fold 1
Train size: 5452
Validation size: 1818
Test size: 3635
Fold 2
Train size: 5452
Validation size: 1818
Test size: 3635
Fold 3
Train size: 5452
Validation size: 1818
Test size: 3635


# Define our model mobilenet

In [13]:
def get_model(name):
    if name == "mobilenet":
        model = models.mobilenet_v2(pretrained=True)
        # Freeze all parameters
        for param in model.parameters():
            param.requires_grad = False
        # Replace the classifier to output 2 classes
        model.classifier[1] = nn.Linear(model.last_channel, 2)
    else:
        raise ValueError("Model name must be 'mobilenet'")
    return model

# Training function

In [14]:
def TrainingModels(model, train_loader, criterion, optimizer):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for images, labels in tqdm(train_loader, desc="Training", leave=False):
        images, labels = images.to(device), labels.to(device)
        
        outputs = model(images)
        loss = criterion(outputs, labels)  #loss function used to compute the error between predictions and true labels
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, preds = torch.max(outputs, 1) # max score from the scores of two classes
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc




# Eval function

In [15]:
def evaluate(model, data_loader, criterion):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in tqdm(data_loader, desc="Evaluating", leave=False):
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc

# Optimize the Learning rate using Optuna

In [16]:
def LR_optimization(trial: Trial):
    lr = trial.suggest_loguniform("lr", 1e-5, 1e-2)
    
    # Iterate over folds
    fold_results = []
    for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
        print(f"\nFold {fold_idx + 1}")
        
        train_size = int(0.75 * len(train_val_idx))
        train_idx = train_val_idx[:train_size]
        val_idx = train_val_idx[train_size:]

        train_set = Subset(combinedData, train_idx)
        val_set = Subset(combinedData, val_idx)
        test_set = Subset(combinedData, test_idx)

        train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
        val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
        test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

        
        for model_name in ["mobilenet"]:
            print(f"\nTraining model: {model_name.upper()} on Fold {fold_idx + 1}")
            
            # Initialize model
            model = get_model(model_name).to(device)
            criterion = nn.CrossEntropyLoss()
            optimizer = optim.Adam(model.parameters(), lr=lr)

            for epoch in range(5):
                current_lr = optimizer.param_groups[0]["lr"]
                print(f"\nEpoch {epoch + 1}/5 | Learning Rate: {current_lr:.6f}")
                
                # Train and evaluate
                train_loss, train_acc = TrainingModels(model, train_loader, criterion, optimizer)
                val_loss, val_acc = evaluate(model, val_loader, criterion)

                print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
                print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")
            
            _, val_acc = evaluate(model, val_loader, criterion)
            fold_results.append(val_acc) 

    mean_val_acc = sum(fold_results) / len(fold_results)
    return mean_val_acc



## Without Fine-tune 

In [17]:
study = optuna.create_study(direction="maximize")
study.optimize(LR_optimization, n_trials=5)

best_trial = study.best_trial
print("\nBest Trial:")
print(f"  Value (Mean Validation Accuracy): {best_trial.value}")
print(f"  Params: {best_trial.params}")

[I 2024-12-24 19:00:36,737] A new study created in memory with name: no-name-a1fbde47-1a9d-4340-be93-dfbacba8b176
<ipython-input-16-fa3930ba039d>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  lr = trial.suggest_loguniform("lr", 1e-5, 1e-2)
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-


Fold 1

Training model: MOBILENET on Fold 1


100%|██████████| 13.6M/13.6M [00:00<00:00, 160MB/s]



Epoch 1/5 | Learning Rate: 0.000484


Train Loss: 0.5996, Train Acc: 0.6820
Val Loss: 1.1021, Val Acc: 0.1700

Epoch 2/5 | Learning Rate: 0.000484


Train Loss: 0.5441, Train Acc: 0.7192
Val Loss: 0.7963, Val Acc: 0.4857

Epoch 3/5 | Learning Rate: 0.000484


Train Loss: 0.5192, Train Acc: 0.7350
Val Loss: 0.5595, Val Acc: 0.7140

Epoch 4/5 | Learning Rate: 0.000484


Train Loss: 0.5105, Train Acc: 0.7452
Val Loss: 0.6762, Val Acc: 0.6133

Epoch 5/5 | Learning Rate: 0.000484


Train Loss: 0.5074, Train Acc: 0.7394
Val Loss: 0.7694, Val Acc: 0.5506



Fold 2

Training model: MOBILENET on Fold 2

Epoch 1/5 | Learning Rate: 0.000484


Train Loss: 0.5979, Train Acc: 0.6838
Val Loss: 1.0629, Val Acc: 0.2107

Epoch 2/5 | Learning Rate: 0.000484


Train Loss: 0.5401, Train Acc: 0.7225
Val Loss: 0.8461, Val Acc: 0.4307

Epoch 3/5 | Learning Rate: 0.000484


Train Loss: 0.5264, Train Acc: 0.7353
Val Loss: 0.5571, Val Acc: 0.7167

Epoch 4/5 | Learning Rate: 0.000484


Train Loss: 0.5091, Train Acc: 0.7474
Val Loss: 0.7310, Val Acc: 0.5556

Epoch 5/5 | Learning Rate: 0.000484


Train Loss: 0.5044, Train Acc: 0.7421
Val Loss: 0.8742, Val Acc: 0.4527



Fold 3

Training model: MOBILENET on Fold 3

Epoch 1/5 | Learning Rate: 0.000484


Train Loss: 0.6002, Train Acc: 0.6763
Val Loss: 1.1551, Val Acc: 0.1436

Epoch 2/5 | Learning Rate: 0.000484


Train Loss: 0.5428, Train Acc: 0.7219
Val Loss: 0.5892, Val Acc: 0.6887

Epoch 3/5 | Learning Rate: 0.000484


Train Loss: 0.5223, Train Acc: 0.7386
Val Loss: 0.5748, Val Acc: 0.6887

Epoch 4/5 | Learning Rate: 0.000484


Train Loss: 0.5165, Train Acc: 0.7432
Val Loss: 0.9745, Val Acc: 0.3669

Epoch 5/5 | Learning Rate: 0.000484


Train Loss: 0.5127, Train Acc: 0.7454
Val Loss: 0.7942, Val Acc: 0.5039


[I 2024-12-24 19:08:48,053] Trial 0 finished with value: 0.5023835716905024 and parameters: {'lr': 0.0004839386939174284}. Best is trial 0 with value: 0.5023835716905024.



Fold 1

Training model: MOBILENET on Fold 1

Epoch 1/5 | Learning Rate: 0.007232


Train Loss: 0.7211, Train Acc: 0.6768
Val Loss: 0.2415, Val Acc: 0.9120

Epoch 2/5 | Learning Rate: 0.007232


Train Loss: 0.7389, Train Acc: 0.6876
Val Loss: 2.1506, Val Acc: 0.1931

Epoch 3/5 | Learning Rate: 0.007232


Train Loss: 0.7419, Train Acc: 0.7074
Val Loss: 0.3060, Val Acc: 0.8652

Epoch 4/5 | Learning Rate: 0.007232


Train Loss: 0.6816, Train Acc: 0.7029
Val Loss: 1.8480, Val Acc: 0.2327

Epoch 5/5 | Learning Rate: 0.007232


Train Loss: 0.7265, Train Acc: 0.6979
Val Loss: 0.5591, Val Acc: 0.7437



Fold 2

Training model: MOBILENET on Fold 2

Epoch 1/5 | Learning Rate: 0.007232


Train Loss: 0.7767, Train Acc: 0.6708
Val Loss: 0.4788, Val Acc: 0.7635

Epoch 2/5 | Learning Rate: 0.007232


Train Loss: 0.6806, Train Acc: 0.6957
Val Loss: 2.2112, Val Acc: 0.1760

Epoch 3/5 | Learning Rate: 0.007232


Train Loss: 0.7364, Train Acc: 0.7100
Val Loss: 0.6283, Val Acc: 0.7024

Epoch 4/5 | Learning Rate: 0.007232


Train Loss: 0.6067, Train Acc: 0.7311
Val Loss: 1.1873, Val Acc: 0.4565

Epoch 5/5 | Learning Rate: 0.007232


Train Loss: 0.6646, Train Acc: 0.7155
Val Loss: 0.6381, Val Acc: 0.6975



Fold 3

Training model: MOBILENET on Fold 3

Epoch 1/5 | Learning Rate: 0.007232


Train Loss: 0.7996, Train Acc: 0.6587
Val Loss: 2.3226, Val Acc: 0.1089

Epoch 2/5 | Learning Rate: 0.007232


Train Loss: 0.6392, Train Acc: 0.7139
Val Loss: 1.1263, Val Acc: 0.4631

Epoch 3/5 | Learning Rate: 0.007232


Train Loss: 0.6893, Train Acc: 0.7113
Val Loss: 0.6121, Val Acc: 0.6876

Epoch 4/5 | Learning Rate: 0.007232


Train Loss: 0.6249, Train Acc: 0.7181
Val Loss: 1.3602, Val Acc: 0.3652

Epoch 5/5 | Learning Rate: 0.007232


Train Loss: 0.7057, Train Acc: 0.7071
Val Loss: 0.5795, Val Acc: 0.7222


[I 2024-12-24 19:16:16,753] Trial 1 finished with value: 0.7211221122112211 and parameters: {'lr': 0.007232401612829719}. Best is trial 1 with value: 0.7211221122112211.



Fold 1

Training model: MOBILENET on Fold 1

Epoch 1/5 | Learning Rate: 0.000432


Train Loss: 0.6026, Train Acc: 0.6781
Val Loss: 0.7304, Val Acc: 0.5231

Epoch 2/5 | Learning Rate: 0.000432


Train Loss: 0.5450, Train Acc: 0.7214
Val Loss: 0.8427, Val Acc: 0.4329

Epoch 3/5 | Learning Rate: 0.000432


Train Loss: 0.5264, Train Acc: 0.7293
Val Loss: 0.7982, Val Acc: 0.4934

Epoch 4/5 | Learning Rate: 0.000432


Train Loss: 0.5159, Train Acc: 0.7375
Val Loss: 0.8574, Val Acc: 0.4505

Epoch 5/5 | Learning Rate: 0.000432


Train Loss: 0.5157, Train Acc: 0.7425
Val Loss: 1.1625, Val Acc: 0.2783



Fold 2

Training model: MOBILENET on Fold 2

Epoch 1/5 | Learning Rate: 0.000432


Train Loss: 0.6031, Train Acc: 0.6759
Val Loss: 1.1662, Val Acc: 0.1524

Epoch 2/5 | Learning Rate: 0.000432


Train Loss: 0.5457, Train Acc: 0.7201
Val Loss: 0.8342, Val Acc: 0.4340

Epoch 3/5 | Learning Rate: 0.000432


Train Loss: 0.5265, Train Acc: 0.7315
Val Loss: 1.1219, Val Acc: 0.2563

Epoch 4/5 | Learning Rate: 0.000432


Train Loss: 0.5137, Train Acc: 0.7438
Val Loss: 0.9968, Val Acc: 0.3482

Epoch 5/5 | Learning Rate: 0.000432


Train Loss: 0.5106, Train Acc: 0.7443
Val Loss: 0.8568, Val Acc: 0.4708



Fold 3

Training model: MOBILENET on Fold 3

Epoch 1/5 | Learning Rate: 0.000432


Train Loss: 0.5860, Train Acc: 0.6946
Val Loss: 1.0953, Val Acc: 0.1832

Epoch 2/5 | Learning Rate: 0.000432


Train Loss: 0.5410, Train Acc: 0.7267
Val Loss: 0.9806, Val Acc: 0.3289

Epoch 3/5 | Learning Rate: 0.000432


Train Loss: 0.5217, Train Acc: 0.7390
Val Loss: 0.7071, Val Acc: 0.5726

Epoch 4/5 | Learning Rate: 0.000432


Train Loss: 0.5122, Train Acc: 0.7489
Val Loss: 0.7506, Val Acc: 0.5479

Epoch 5/5 | Learning Rate: 0.000432


Train Loss: 0.5043, Train Acc: 0.7498
Val Loss: 0.6360, Val Acc: 0.6463


[I 2024-12-24 19:23:44,118] Trial 2 finished with value: 0.4651631829849652 and parameters: {'lr': 0.0004323196868020778}. Best is trial 1 with value: 0.7211221122112211.



Fold 1

Training model: MOBILENET on Fold 1

Epoch 1/5 | Learning Rate: 0.000467


Train Loss: 0.6048, Train Acc: 0.6728
Val Loss: 0.6355, Val Acc: 0.6452

Epoch 2/5 | Learning Rate: 0.000467


Train Loss: 0.5451, Train Acc: 0.7131
Val Loss: 0.7830, Val Acc: 0.4972

Epoch 3/5 | Learning Rate: 0.000467


Train Loss: 0.5266, Train Acc: 0.7296
Val Loss: 0.8824, Val Acc: 0.4384

Epoch 4/5 | Learning Rate: 0.000467


Train Loss: 0.5186, Train Acc: 0.7375
Val Loss: 0.7246, Val Acc: 0.5825

Epoch 5/5 | Learning Rate: 0.000467


Train Loss: 0.5101, Train Acc: 0.7471
Val Loss: 0.8669, Val Acc: 0.4631



Fold 2

Training model: MOBILENET on Fold 2

Epoch 1/5 | Learning Rate: 0.000467


Train Loss: 0.6022, Train Acc: 0.6757
Val Loss: 1.1106, Val Acc: 0.1700

Epoch 2/5 | Learning Rate: 0.000467


Train Loss: 0.5437, Train Acc: 0.7124
Val Loss: 0.6333, Val Acc: 0.6419

Epoch 3/5 | Learning Rate: 0.000467


Train Loss: 0.5238, Train Acc: 0.7344
Val Loss: 1.1029, Val Acc: 0.2838

Epoch 4/5 | Learning Rate: 0.000467


Train Loss: 0.5163, Train Acc: 0.7377
Val Loss: 0.9478, Val Acc: 0.3971

Epoch 5/5 | Learning Rate: 0.000467


Train Loss: 0.5075, Train Acc: 0.7517
Val Loss: 0.8997, Val Acc: 0.4340



Fold 3

Training model: MOBILENET on Fold 3

Epoch 1/5 | Learning Rate: 0.000467


Train Loss: 0.5970, Train Acc: 0.6865
Val Loss: 0.5215, Val Acc: 0.7811

Epoch 2/5 | Learning Rate: 0.000467


Train Loss: 0.5409, Train Acc: 0.7207
Val Loss: 0.6534, Val Acc: 0.6221

Epoch 3/5 | Learning Rate: 0.000467


Train Loss: 0.5184, Train Acc: 0.7370
Val Loss: 0.8107, Val Acc: 0.4780

Epoch 4/5 | Learning Rate: 0.000467


Train Loss: 0.5113, Train Acc: 0.7447
Val Loss: 0.8842, Val Acc: 0.4301

Epoch 5/5 | Learning Rate: 0.000467


Train Loss: 0.5162, Train Acc: 0.7417
Val Loss: 0.7408, Val Acc: 0.5495


[I 2024-12-24 19:31:12,882] Trial 3 finished with value: 0.48221488815548225 and parameters: {'lr': 0.0004667085451589679}. Best is trial 1 with value: 0.7211221122112211.



Fold 1

Training model: MOBILENET on Fold 1

Epoch 1/5 | Learning Rate: 0.001875


Train Loss: 0.5855, Train Acc: 0.6919
Val Loss: 1.1689, Val Acc: 0.2717

Epoch 2/5 | Learning Rate: 0.001875


Train Loss: 0.5401, Train Acc: 0.7317
Val Loss: 0.7162, Val Acc: 0.5842

Epoch 3/5 | Learning Rate: 0.001875


Train Loss: 0.5357, Train Acc: 0.7383
Val Loss: 0.5851, Val Acc: 0.6991

Epoch 4/5 | Learning Rate: 0.001875


Train Loss: 0.5331, Train Acc: 0.7342
Val Loss: 1.2885, Val Acc: 0.2954

Epoch 5/5 | Learning Rate: 0.001875


Train Loss: 0.5678, Train Acc: 0.7214
Val Loss: 1.5984, Val Acc: 0.2041



Fold 2

Training model: MOBILENET on Fold 2

Epoch 1/5 | Learning Rate: 0.001875


Train Loss: 0.5842, Train Acc: 0.6957
Val Loss: 1.1323, Val Acc: 0.3240

Epoch 2/5 | Learning Rate: 0.001875


Train Loss: 0.5547, Train Acc: 0.7289
Val Loss: 0.8908, Val Acc: 0.4813

Epoch 3/5 | Learning Rate: 0.001875


Train Loss: 0.5321, Train Acc: 0.7394
Val Loss: 1.2943, Val Acc: 0.3113

Epoch 4/5 | Learning Rate: 0.001875


Train Loss: 0.5369, Train Acc: 0.7394
Val Loss: 0.7397, Val Acc: 0.5930

Epoch 5/5 | Learning Rate: 0.001875


Train Loss: 0.5178, Train Acc: 0.7427
Val Loss: 0.8256, Val Acc: 0.5446



Fold 3

Training model: MOBILENET on Fold 3

Epoch 1/5 | Learning Rate: 0.001875


Train Loss: 0.5968, Train Acc: 0.6917
Val Loss: 0.6066, Val Acc: 0.6656

Epoch 2/5 | Learning Rate: 0.001875


Train Loss: 0.5364, Train Acc: 0.7278
Val Loss: 0.9213, Val Acc: 0.4571

Epoch 3/5 | Learning Rate: 0.001875


Train Loss: 0.5654, Train Acc: 0.7302
Val Loss: 0.6806, Val Acc: 0.6353

Epoch 4/5 | Learning Rate: 0.001875


Train Loss: 0.5206, Train Acc: 0.7436
Val Loss: 1.4591, Val Acc: 0.2305

Epoch 5/5 | Learning Rate: 0.001875


Train Loss: 0.5360, Train Acc: 0.7353
Val Loss: 0.5211, Val Acc: 0.7398


[I 2024-12-24 19:38:39,462] Trial 4 finished with value: 0.4961496149614962 and parameters: {'lr': 0.0018754078905789996}. Best is trial 1 with value: 0.7211221122112211.



Best Trial:
  Value (Mean Validation Accuracy): 0.7211221122112211
  Params: {'lr': 0.007232401612829719}


# After the Optuna optimization process, we will use the best trial to set the learning rate

In [18]:
# Best learning rate from Optuna
best_lr = 0.007232401612829719

In [19]:
final_results = {}

for model_name in ["mobilenet"]:
    print(f"\nTraining model: {model_name.upper()} with best learning rate {best_lr}")
    
    # Initialize model
    model = get_model(model_name).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=best_lr)
    
    # Create DataLoaders (assuming combinedData is split into train and test datasets)
    train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

    # Train the model
    for epoch in range(10):  # Example: 10 epochs
        print(f"\nEpoch {epoch + 1}/10")
        
        # Train and evaluate
        train_loss, train_acc = TrainingModels(model, train_loader, criterion, optimizer)
        print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
    
    # Final evaluation on the test set
    test_loss, test_acc = evaluate(model, test_loader, criterion)
    print(f"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.4f}")
    
    # Store results
    final_results[model_name] = {
        "Test Loss": test_loss,
        "Test Accuracy": test_acc
    }

# Print final results
print("\nFinal Results:")
for model_name, metrics in final_results.items():
    print(f"{model_name.upper()}:")
    for metric, value in metrics.items():
        print(f"  {metric}: {value:.4f}")


Training model: MOBILENET with best learning rate 0.007232401612829719

Epoch 1/10


Train Loss: 0.7637, Train Acc: 0.6709

Epoch 2/10


Train Loss: 0.6161, Train Acc: 0.7117

Epoch 3/10


Train Loss: 0.6679, Train Acc: 0.7098

Epoch 4/10


Train Loss: 0.7015, Train Acc: 0.7062

Epoch 5/10


Train Loss: 0.7004, Train Acc: 0.7063

Epoch 6/10


Train Loss: 0.7422, Train Acc: 0.7085

Epoch 7/10


Train Loss: 0.7132, Train Acc: 0.7129

Epoch 8/10


Train Loss: 0.7121, Train Acc: 0.7129

Epoch 9/10


Train Loss: 0.8014, Train Acc: 0.7062

Epoch 10/10


Train Loss: 0.7198, Train Acc: 0.7115


Test Loss: 1.1034, Test Acc: 0.5827

Final Results:
MOBILENET:
  Test Loss: 1.1034
  Test Accuracy: 0.5827


In [20]:
# Function to evaluate the model and get performance metrics
def evaluate_model(model, dataloader):
    model.eval()
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            
            outputs = model(inputs)
            _, predicted = torch.max(outputs, 1)
            
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return np.array(all_preds), np.array(all_labels)

# Initialize cross-validation metrics storage
confusion_matrices = []
accuracies = []
precisions = []
recalls = []
f1_scores = []

best_lr = 0.007232401612829719

for model_name in ["mobilenet"]:
    print(f"\nTraining model: {model_name.upper()} with best learning rate {best_lr}")
    
    for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
        print(f"Fold {fold_idx + 1}")

        train_size = int(0.75 * len(train_val_idx))
        train_idx = train_val_idx[:train_size]
        val_idx = train_val_idx[train_size:]

        train_set = Subset(combinedData, train_idx)
        val_set = Subset(combinedData, val_idx)
        test_set = Subset(combinedData, test_idx)

        train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
        val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
        test_loader = DataLoader(test_set, batch_size=32, shuffle=False)
        
        
        model = get_model(model_name).to(device)
        optimizer = optim.Adam(model.parameters(), lr=best_lr)
        criterion = nn.CrossEntropyLoss()

        # Train the model
        for epoch in range(10):
            model.train()
            running_loss = 0.0
            for inputs, labels in train_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()
                running_loss += loss.item()

            print(f"Epoch {epoch+1}/10, Loss: {running_loss / len(train_loader):.4f}")

    
        preds, labels = evaluate_model(model, test_loader)

        
        accuracy = accuracy_score(labels, preds)
        precision = precision_score(labels, preds, average='weighted', zero_division=0)
        recall = recall_score(labels, preds, average='weighted', zero_division=0)
        f1 = f1_score(labels, preds, average='weighted', zero_division=0)
        cm = confusion_matrix(labels, preds)

        # Store metrics for the fold
        confusion_matrices.append(cm)
        accuracies.append(accuracy)
        precisions.append(precision)
        recalls.append(recall)
        f1_scores.append(f1)

        print(f"Fold {fold_idx + 1} - Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-Score: {f1:.4f}")
        print(f"Confusion Matrix:\n{cm}\n")

    # Average metrics across folds
    avg_accuracy = np.mean(accuracies)
    avg_precision = np.mean(precisions)
    avg_recall = np.mean(recalls)
    avg_f1_score = np.mean(f1_scores)
    avg_confusion_matrix = np.mean(confusion_matrices, axis=0)

    # Print final average metrics for the model
    print(f"\nFinal Results for {model_name.upper()}:")
    print(f"Average Accuracy: {avg_accuracy:.4f}")
    print(f"Average Precision: {avg_precision:.4f}")
    print(f"Average Recall: {avg_recall:.4f}")
    print(f"Average F1-Score: {avg_f1_score:.4f}")
    print(f"Average Confusion Matrix:\n{avg_confusion_matrix}")


Training model: MOBILENET with best learning rate 0.007232401612829719
Fold 1
Epoch 1/10, Loss: 0.7662
Epoch 2/10, Loss: 0.6707
Epoch 3/10, Loss: 0.7132
Epoch 4/10, Loss: 0.6329
Epoch 5/10, Loss: 0.6383
Epoch 6/10, Loss: 0.7477
Epoch 7/10, Loss: 0.7417
Epoch 8/10, Loss: 0.6694
Epoch 9/10, Loss: 0.8421
Epoch 10/10, Loss: 0.7209
Fold 1 - Accuracy: 0.7073, Precision: 0.7079, Recall: 0.7073, F1-Score: 0.7066
Confusion Matrix:
[[1399  465]
 [ 599 1172]]

Fold 2


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Epoch 1/10, Loss: 0.7659
Epoch 2/10, Loss: 0.6756
Epoch 3/10, Loss: 0.7129
Epoch 4/10, Loss: 0.7410
Epoch 5/10, Loss: 0.6993
Epoch 6/10, Loss: 0.7726
Epoch 7/10, Loss: 0.7592
Epoch 8/10, Loss: 0.6633
Epoch 9/10, Loss: 0.6915
Epoch 10/10, Loss: 0.6897
Fold 2 - Accuracy: 0.7254, Precision: 0.7264, Recall: 0.7254, F1-Score: 0.7253
Confusion Matrix:
[[1281  553]
 [ 445 1356]]

Fold 3


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Epoch 1/10, Loss: 0.7083
Epoch 2/10, Loss: 0.6950
Epoch 3/10, Loss: 0.6624
Epoch 4/10, Loss: 0.7241
Epoch 5/10, Loss: 0.7068
Epoch 6/10, Loss: 0.6557
Epoch 7/10, Loss: 0.6992
Epoch 8/10, Loss: 0.6905
Epoch 9/10, Loss: 0.7192
Epoch 10/10, Loss: 0.7413
Fold 3 - Accuracy: 0.6790, Precision: 0.7387, Recall: 0.6790, F1-Score: 0.6557
Confusion Matrix:
[[ 751 1043]
 [ 124 1717]]


Final Results for MOBILENET:
Average Accuracy: 0.7039
Average Precision: 0.7243
Average Recall: 0.7039
Average F1-Score: 0.6959
Average Confusion Matrix:
[[1143.66666667  687.        ]
 [ 389.33333333 1415.        ]]


## Fine-tuning 

## Applying Fine-tune

In [17]:
# Fine-tune
def get_model(name):
    if name == "mobilenet":
        # Load the pretrained MobileNet model
        model = models.mobilenet_v2(pretrained=True)
        
        # Freeze all layers initially
        for param in model.parameters():
            param.requires_grad = False
        
        # Fine-tune the last 5 layers
        # 1. Unfreeze the last 5 convolutional blocks in the feature extractor
        for param in model.features[-5:].parameters():
            param.requires_grad = True
        
        # 2. Modify the classifier for the desired number of output classes
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, 2)
        
        # 3. Ensure the classifier layer is trainable
        for param in model.classifier.parameters():
            param.requires_grad = True
        
        # Print the number of trainable parameters
        trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
        print(f"Total trainable parameters: {trainable_params:,}")
        
    else:
        raise ValueError("Model name must be 'mobilenet'")
    
    return model


## Training Function 

In [21]:
# Fine-tune

def TrainingModels(model, train_loader, criterion, optimizer):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    
    # Add gradient clipping to prevent exploding gradients
    max_grad_norm = 1.0
    
    for images, labels in tqdm(train_loader, desc="Training", leave=False):
        images, labels = images.to(device), labels.to(device)
        
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        
        # Clip gradients
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, preds = torch.max(outputs, 1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc

In [22]:
def evaluate(model, data_loader, criterion):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in tqdm(data_loader, desc="Evaluating", leave=False):
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc

In [23]:
# Fine-tune

def LR_optimization(trial: Trial):
    # Use a smaller learning rate range for fine-tuning
    lr = trial.suggest_loguniform("lr", 1e-6, 1e-3)
    
    # Rest of the function remains the same
    fold_results = []
    for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
        print(f"\nFold {fold_idx + 1}")
        
        train_size = int(0.75 * len(train_val_idx))
        train_idx = train_val_idx[:train_size]
        val_idx = train_val_idx[train_size:]

        train_set = Subset(combinedData, train_idx)
        val_set = Subset(combinedData, val_idx)
        test_set = Subset(combinedData, test_idx)

        train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
        val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
        test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

        for model_name in ["mobilenet"]:
            print(f"\nFine-tuning model: {model_name.upper()} on Fold {fold_idx + 1}")
            
            model = get_model(model_name).to(device)
            criterion = nn.CrossEntropyLoss()
            
            # Use a smaller weight decay for fine-tuning
            optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
            
            # Add learning rate scheduler for fine-tuning
            scheduler = optim.lr_scheduler.ReduceLROnPlateau(
                optimizer, mode='max', factor=0.5, patience=2, verbose=True
            )

            for epoch in range(5):
                current_lr = optimizer.param_groups[0]["lr"]
                print(f"\nEpoch {epoch + 1}/5 | Learning Rate: {current_lr:.6f}")
                
                train_loss, train_acc = TrainingModels(model, train_loader, criterion, optimizer)
                val_loss, val_acc = evaluate(model, val_loader, criterion)
                
                # Update learning rate based on validation accuracy
                scheduler.step(val_acc)

                print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
                print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")
            
            _, val_acc = evaluate(model, val_loader, criterion)
            fold_results.append(val_acc)

    mean_val_acc = sum(fold_results) / len(fold_results)
    return mean_val_acc

In [24]:
study = optuna.create_study(direction="maximize")
study.optimize(LR_optimization, n_trials=5)

best_trial = study.best_trial
print("\nBest Trial:")
print(f"  Value (Mean Validation Accuracy): {best_trial.value}")
print(f"  Params: {best_trial.params}")

[I 2024-12-24 21:50:49,214] A new study created in memory with name: no-name-67461f74-e141-4a5b-aa41-ec2a28351a19
<ipython-input-23-400e3bc04bdc>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  lr = trial.suggest_loguniform("lr", 1e-6, 1e-3)



Fold 1

Fine-tuning model: MOBILENET on Fold 1
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000085


Train Loss: 0.4322, Train Acc: 0.7801
Val Loss: 0.5501, Val Acc: 0.7118

Epoch 2/5 | Learning Rate: 0.000085


Train Loss: 0.2560, Train Acc: 0.8914
Val Loss: 0.6317, Val Acc: 0.7063

Epoch 3/5 | Learning Rate: 0.000085


Train Loss: 0.1644, Train Acc: 0.9321
Val Loss: 0.6713, Val Acc: 0.7387

Epoch 4/5 | Learning Rate: 0.000085


Train Loss: 0.1031, Train Acc: 0.9628
Val Loss: 0.6698, Val Acc: 0.8042

Epoch 5/5 | Learning Rate: 0.000085


Train Loss: 0.0583, Train Acc: 0.9785
Val Loss: 0.8823, Val Acc: 0.7783



Fold 2

Fine-tuning model: MOBILENET on Fold 2
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000085


Train Loss: 0.4399, Train Acc: 0.7832
Val Loss: 0.6095, Val Acc: 0.6881

Epoch 2/5 | Learning Rate: 0.000085


Train Loss: 0.2383, Train Acc: 0.9004
Val Loss: 0.6091, Val Acc: 0.7189

Epoch 3/5 | Learning Rate: 0.000085


Train Loss: 0.1487, Train Acc: 0.9404
Val Loss: 0.8229, Val Acc: 0.7206

Epoch 4/5 | Learning Rate: 0.000085


Train Loss: 0.0876, Train Acc: 0.9650
Val Loss: 0.7041, Val Acc: 0.7932

Epoch 5/5 | Learning Rate: 0.000085


Train Loss: 0.0477, Train Acc: 0.9809
Val Loss: 1.0224, Val Acc: 0.7514



Fold 3

Fine-tuning model: MOBILENET on Fold 3
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000085


Train Loss: 0.4331, Train Acc: 0.7852
Val Loss: 0.4553, Val Acc: 0.7453

Epoch 2/5 | Learning Rate: 0.000085


Train Loss: 0.2547, Train Acc: 0.8910
Val Loss: 0.5321, Val Acc: 0.7574

Epoch 3/5 | Learning Rate: 0.000085


Train Loss: 0.1598, Train Acc: 0.9340
Val Loss: 0.5976, Val Acc: 0.7706

Epoch 4/5 | Learning Rate: 0.000085


Train Loss: 0.1014, Train Acc: 0.9624
Val Loss: 0.9983, Val Acc: 0.6980

Epoch 5/5 | Learning Rate: 0.000085


Train Loss: 0.0642, Train Acc: 0.9767
Val Loss: 1.1097, Val Acc: 0.6854


[I 2024-12-24 21:59:47,559] Trial 0 finished with value: 0.7383571690502384 and parameters: {'lr': 8.496036792968012e-05}. Best is trial 0 with value: 0.7383571690502384.



Fold 1

Fine-tuning model: MOBILENET on Fold 1
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000187


Train Loss: 0.4005, Train Acc: 0.8098
Val Loss: 0.3759, Val Acc: 0.8333

Epoch 2/5 | Learning Rate: 0.000187


Train Loss: 0.2258, Train Acc: 0.9068
Val Loss: 0.4947, Val Acc: 0.8146

Epoch 3/5 | Learning Rate: 0.000187


Train Loss: 0.1417, Train Acc: 0.9446
Val Loss: 0.9140, Val Acc: 0.7695

Epoch 4/5 | Learning Rate: 0.000187


Train Loss: 0.0755, Train Acc: 0.9723
Val Loss: 1.4732, Val Acc: 0.6876

Epoch 5/5 | Learning Rate: 0.000094


Train Loss: 0.0324, Train Acc: 0.9868
Val Loss: 0.8243, Val Acc: 0.8025



Fold 2

Fine-tuning model: MOBILENET on Fold 2
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000187


Train Loss: 0.3890, Train Acc: 0.8179
Val Loss: 0.7514, Val Acc: 0.6771

Epoch 2/5 | Learning Rate: 0.000187


Train Loss: 0.2171, Train Acc: 0.9151
Val Loss: 0.5388, Val Acc: 0.7838

Epoch 3/5 | Learning Rate: 0.000187


Train Loss: 0.1387, Train Acc: 0.9452
Val Loss: 0.5676, Val Acc: 0.8135

Epoch 4/5 | Learning Rate: 0.000187


Train Loss: 0.0884, Train Acc: 0.9655
Val Loss: 1.2767, Val Acc: 0.7112

Epoch 5/5 | Learning Rate: 0.000187


Train Loss: 0.0542, Train Acc: 0.9802
Val Loss: 1.5436, Val Acc: 0.6815



Fold 3

Fine-tuning model: MOBILENET on Fold 3
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000187


Train Loss: 0.3971, Train Acc: 0.8081
Val Loss: 0.5432, Val Acc: 0.7618

Epoch 2/5 | Learning Rate: 0.000187


Train Loss: 0.2275, Train Acc: 0.9048
Val Loss: 0.4095, Val Acc: 0.8410

Epoch 3/5 | Learning Rate: 0.000187


Train Loss: 0.1279, Train Acc: 0.9527
Val Loss: 1.1926, Val Acc: 0.6452

Epoch 4/5 | Learning Rate: 0.000187


Train Loss: 0.0809, Train Acc: 0.9694
Val Loss: 0.4820, Val Acc: 0.8592

Epoch 5/5 | Learning Rate: 0.000187


Train Loss: 0.0655, Train Acc: 0.9778
Val Loss: 1.4873, Val Acc: 0.7327


[I 2024-12-24 22:08:26,125] Trial 1 finished with value: 0.7389072240557389 and parameters: {'lr': 0.00018721286755151963}. Best is trial 1 with value: 0.7389072240557389.



Fold 1

Fine-tuning model: MOBILENET on Fold 1
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000002


Train Loss: 0.6542, Train Acc: 0.6350
Val Loss: 0.9599, Val Acc: 0.1100

Epoch 2/5 | Learning Rate: 0.000002


Train Loss: 0.6080, Train Acc: 0.6680
Val Loss: 0.9582, Val Acc: 0.1562

Epoch 3/5 | Learning Rate: 0.000002


Train Loss: 0.5743, Train Acc: 0.6968
Val Loss: 0.8914, Val Acc: 0.2662

Epoch 4/5 | Learning Rate: 0.000002


Train Loss: 0.5467, Train Acc: 0.7129
Val Loss: 0.9127, Val Acc: 0.2981

Epoch 5/5 | Learning Rate: 0.000002


Train Loss: 0.5230, Train Acc: 0.7309
Val Loss: 0.8223, Val Acc: 0.4279



Fold 2

Fine-tuning model: MOBILENET on Fold 2
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000002


Train Loss: 0.6408, Train Acc: 0.6368
Val Loss: 0.8826, Val Acc: 0.2129

Epoch 2/5 | Learning Rate: 0.000002


Train Loss: 0.5866, Train Acc: 0.6906
Val Loss: 0.8996, Val Acc: 0.2365

Epoch 3/5 | Learning Rate: 0.000002


Train Loss: 0.5534, Train Acc: 0.7133
Val Loss: 0.8719, Val Acc: 0.3212

Epoch 4/5 | Learning Rate: 0.000002


Train Loss: 0.5219, Train Acc: 0.7425
Val Loss: 0.8271, Val Acc: 0.4186

Epoch 5/5 | Learning Rate: 0.000002


Train Loss: 0.4963, Train Acc: 0.7529
Val Loss: 0.7659, Val Acc: 0.5017



Fold 3

Fine-tuning model: MOBILENET on Fold 3
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000002


Train Loss: 0.6717, Train Acc: 0.5842
Val Loss: 0.8490, Val Acc: 0.2673

Epoch 2/5 | Learning Rate: 0.000002


Train Loss: 0.6053, Train Acc: 0.6742
Val Loss: 0.8996, Val Acc: 0.2503

Epoch 3/5 | Learning Rate: 0.000002


Train Loss: 0.5714, Train Acc: 0.6944
Val Loss: 0.8930, Val Acc: 0.2937

Epoch 4/5 | Learning Rate: 0.000002


Train Loss: 0.5400, Train Acc: 0.7225
Val Loss: 0.8820, Val Acc: 0.3460

Epoch 5/5 | Learning Rate: 0.000002


Train Loss: 0.5187, Train Acc: 0.7388
Val Loss: 0.8785, Val Acc: 0.3828


[I 2024-12-24 22:17:20,891] Trial 2 finished with value: 0.43747708104143745 and parameters: {'lr': 2.3354619208719656e-06}. Best is trial 1 with value: 0.7389072240557389.



Fold 1

Fine-tuning model: MOBILENET on Fold 1
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000003


Train Loss: 0.6345, Train Acc: 0.6471
Val Loss: 0.9221, Val Acc: 0.1815

Epoch 2/5 | Learning Rate: 0.000003


Train Loss: 0.5841, Train Acc: 0.6864
Val Loss: 0.8881, Val Acc: 0.2591

Epoch 3/5 | Learning Rate: 0.000003


Train Loss: 0.5530, Train Acc: 0.7071
Val Loss: 0.8640, Val Acc: 0.3267

Epoch 4/5 | Learning Rate: 0.000003


Train Loss: 0.5220, Train Acc: 0.7311
Val Loss: 0.8170, Val Acc: 0.4197

Epoch 5/5 | Learning Rate: 0.000003


Train Loss: 0.4915, Train Acc: 0.7606
Val Loss: 0.7777, Val Acc: 0.4785



Fold 2

Fine-tuning model: MOBILENET on Fold 2
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000003


Train Loss: 0.6344, Train Acc: 0.6550
Val Loss: 0.9825, Val Acc: 0.1133

Epoch 2/5 | Learning Rate: 0.000003


Train Loss: 0.5918, Train Acc: 0.6821
Val Loss: 0.9530, Val Acc: 0.1892

Epoch 3/5 | Learning Rate: 0.000003


Train Loss: 0.5594, Train Acc: 0.7019
Val Loss: 0.8712, Val Acc: 0.3377

Epoch 4/5 | Learning Rate: 0.000003


Train Loss: 0.5274, Train Acc: 0.7311
Val Loss: 0.8643, Val Acc: 0.3867

Epoch 5/5 | Learning Rate: 0.000003


Train Loss: 0.4994, Train Acc: 0.7491
Val Loss: 0.8040, Val Acc: 0.4631



Fold 3

Fine-tuning model: MOBILENET on Fold 3
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000003


Train Loss: 0.6482, Train Acc: 0.6332
Val Loss: 0.8848, Val Acc: 0.1832

Epoch 2/5 | Learning Rate: 0.000003


Train Loss: 0.5841, Train Acc: 0.6972
Val Loss: 0.9062, Val Acc: 0.2024

Epoch 3/5 | Learning Rate: 0.000003


Train Loss: 0.5517, Train Acc: 0.7150
Val Loss: 0.8845, Val Acc: 0.2943

Epoch 4/5 | Learning Rate: 0.000003


Train Loss: 0.5254, Train Acc: 0.7295
Val Loss: 0.8354, Val Acc: 0.3977

Epoch 5/5 | Learning Rate: 0.000003


Train Loss: 0.4998, Train Acc: 0.7496
Val Loss: 0.7929, Val Acc: 0.4807


[I 2024-12-24 22:26:00,151] Trial 3 finished with value: 0.47414741474147415 and parameters: {'lr': 2.639979614237705e-06}. Best is trial 1 with value: 0.7389072240557389.



Fold 1

Fine-tuning model: MOBILENET on Fold 1
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000001


Train Loss: 0.9370, Train Acc: 0.3496
Val Loss: 0.3999, Val Acc: 0.9752

Epoch 2/5 | Learning Rate: 0.000001


Train Loss: 0.8180, Train Acc: 0.3942
Val Loss: 0.4709, Val Acc: 0.9268

Epoch 3/5 | Learning Rate: 0.000001


Train Loss: 0.7230, Train Acc: 0.5090
Val Loss: 0.5160, Val Acc: 0.8493

Epoch 4/5 | Learning Rate: 0.000001


Train Loss: 0.6504, Train Acc: 0.6223
Val Loss: 0.6150, Val Acc: 0.6865

Epoch 5/5 | Learning Rate: 0.000001


Train Loss: 0.6069, Train Acc: 0.6741
Val Loss: 0.6203, Val Acc: 0.6738



Fold 2

Fine-tuning model: MOBILENET on Fold 2
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000001


Train Loss: 0.7391, Train Acc: 0.4626
Val Loss: 0.6334, Val Acc: 0.6733

Epoch 2/5 | Learning Rate: 0.000001


Train Loss: 0.6744, Train Acc: 0.5807
Val Loss: 0.7137, Val Acc: 0.5033

Epoch 3/5 | Learning Rate: 0.000001


Train Loss: 0.6290, Train Acc: 0.6521
Val Loss: 0.7495, Val Acc: 0.4576

Epoch 4/5 | Learning Rate: 0.000001


Train Loss: 0.5982, Train Acc: 0.6803
Val Loss: 0.7960, Val Acc: 0.3905

Epoch 5/5 | Learning Rate: 0.000001


Train Loss: 0.5805, Train Acc: 0.6999
Val Loss: 0.7995, Val Acc: 0.3966



Fold 3

Fine-tuning model: MOBILENET on Fold 3
Total trainable parameters: 1,683,906

Epoch 1/5 | Learning Rate: 0.000001


Train Loss: 0.6940, Train Acc: 0.5473
Val Loss: 0.7617, Val Acc: 0.3828

Epoch 2/5 | Learning Rate: 0.000001


Train Loss: 0.6446, Train Acc: 0.6293
Val Loss: 0.7956, Val Acc: 0.3278

Epoch 3/5 | Learning Rate: 0.000001


Train Loss: 0.6079, Train Acc: 0.6722
Val Loss: 0.8356, Val Acc: 0.2816

Epoch 4/5 | Learning Rate: 0.000001


Train Loss: 0.5802, Train Acc: 0.6911
Val Loss: 0.8471, Val Acc: 0.2921

Epoch 5/5 | Learning Rate: 0.000001


Train Loss: 0.5649, Train Acc: 0.7030
Val Loss: 0.8640, Val Acc: 0.2794


[I 2024-12-24 22:34:40,661] Trial 4 finished with value: 0.44994499449944997 and parameters: {'lr': 1.2424743744259802e-06}. Best is trial 1 with value: 0.7389072240557389.



Best Trial:
  Value (Mean Validation Accuracy): 0.7389072240557389
  Params: {'lr': 0.00018721286755151963}


# After the Optuna optimization process, we will use the best trial to set the learning rate

In [25]:
# Best learning rate from Optuna
best_lr = 0.0009289966381913214

In [26]:
final_results = {}

for model_name in ["mobilenet"]:
    print(f"\nTraining model: {model_name.upper()} with best learning rate {best_lr}")
    
    # Initialize model
    model = get_model(model_name).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=best_lr)
    
    # Create DataLoaders (assuming combinedData is split into train and test datasets)
    train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

    # Train the model
    for epoch in range(10):  # Example: 10 epochs
        print(f"\nEpoch {epoch + 1}/10")
        
        # Train and evaluate
        train_loss, train_acc = TrainingModels(model, train_loader, criterion, optimizer)
        print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
    
    # Final evaluation on the test set
    test_loss, test_acc = evaluate(model, test_loader, criterion)
    print(f"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.4f}")
    
    # Store results
    final_results[model_name] = {
        "Test Loss": test_loss,
        "Test Accuracy": test_acc
    }

# Print final results
print("\nFinal Results:")
for model_name, metrics in final_results.items():
    print(f"{model_name.upper()}:")
    for metric, value in metrics.items():
        print(f"  {metric}: {value:.4f}")


Training model: MOBILENET with best learning rate 0.0009289966381913214
Total trainable parameters: 1,683,906

Epoch 1/10


Train Loss: 0.3825, Train Acc: 0.8309

Epoch 2/10


Train Loss: 0.2185, Train Acc: 0.9136

Epoch 3/10


Train Loss: 0.1644, Train Acc: 0.9384

Epoch 4/10


Train Loss: 0.1157, Train Acc: 0.9578

Epoch 5/10


Train Loss: 0.0730, Train Acc: 0.9736

Epoch 6/10


Train Loss: 0.0562, Train Acc: 0.9791

Epoch 7/10


Train Loss: 0.0514, Train Acc: 0.9842

Epoch 8/10


Train Loss: 0.0335, Train Acc: 0.9861

Epoch 9/10


Train Loss: 0.0424, Train Acc: 0.9873

Epoch 10/10


Train Loss: 0.0268, Train Acc: 0.9910


Test Loss: 0.5699, Test Acc: 0.8946

Final Results:
MOBILENET:
  Test Loss: 0.5699
  Test Accuracy: 0.8946


In [27]:
# Function to evaluate the model and get performance metrics
def evaluate_model(model, dataloader):
    model.eval()
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            
            outputs = model(inputs)
            _, predicted = torch.max(outputs, 1)
            
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return np.array(all_preds), np.array(all_labels)

# Initialize cross-validation metrics storage
confusion_matrices = []
accuracies = []
precisions = []
recalls = []
f1_scores = []

best_lr = 0.0009289966381913214

for model_name in ["mobilenet"]:
    print(f"\nTraining model: {model_name.upper()} with best learning rate {best_lr}")
    
    for fold_idx, (train_val_idx, test_idx) in enumerate(kf.split(np.arange(samples))):
        print(f"Fold {fold_idx + 1}")

        train_size = int(0.75 * len(train_val_idx))
        train_idx = train_val_idx[:train_size]
        val_idx = train_val_idx[train_size:]

        train_set = Subset(combinedData, train_idx)
        val_set = Subset(combinedData, val_idx)
        test_set = Subset(combinedData, test_idx)

        train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
        val_loader = DataLoader(val_set, batch_size=32, shuffle=False)
        test_loader = DataLoader(test_set, batch_size=32, shuffle=False)
        
        
        model = get_model(model_name).to(device)
        optimizer = optim.Adam(model.parameters(), lr=best_lr)
        criterion = nn.CrossEntropyLoss()

        # Train the model
        for epoch in range(10):
            model.train()
            running_loss = 0.0
            for inputs, labels in train_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()
                running_loss += loss.item()

            print(f"Epoch {epoch+1}/10, Loss: {running_loss / len(train_loader):.4f}")

    
        preds, labels = evaluate_model(model, test_loader)

        
        accuracy = accuracy_score(labels, preds)
        precision = precision_score(labels, preds, average='weighted', zero_division=0)
        recall = recall_score(labels, preds, average='weighted', zero_division=0)
        f1 = f1_score(labels, preds, average='weighted', zero_division=0)
        cm = confusion_matrix(labels, preds)

        # Store metrics for the fold
        confusion_matrices.append(cm)
        accuracies.append(accuracy)
        precisions.append(precision)
        recalls.append(recall)
        f1_scores.append(f1)

        print(f"Fold {fold_idx + 1} - Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-Score: {f1:.4f}")
        print(f"Confusion Matrix:\n{cm}\n")

    # Average metrics across folds
    avg_accuracy = np.mean(accuracies)
    avg_precision = np.mean(precisions)
    avg_recall = np.mean(recalls)
    avg_f1_score = np.mean(f1_scores)
    avg_confusion_matrix = np.mean(confusion_matrices, axis=0)

    # Print final average metrics for the model
    print(f"\nFinal Results for {model_name.upper()}:")
    print(f"Average Accuracy: {avg_accuracy:.4f}")
    print(f"Average Precision: {avg_precision:.4f}")
    print(f"Average Recall: {avg_recall:.4f}")
    print(f"Average F1-Score: {avg_f1_score:.4f}")
    print(f"Average Confusion Matrix:\n{avg_confusion_matrix}")


Training model: MOBILENET with best learning rate 0.0009289966381913214
Fold 1
Total trainable parameters: 1,683,906
Epoch 1/10, Loss: 0.3863
Epoch 2/10, Loss: 0.2188
Epoch 3/10, Loss: 0.1494
Epoch 4/10, Loss: 0.1101
Epoch 5/10, Loss: 0.0855
Epoch 6/10, Loss: 0.0826
Epoch 7/10, Loss: 0.0491
Epoch 8/10, Loss: 0.0340
Epoch 9/10, Loss: 0.0328
Epoch 10/10, Loss: 0.0334
Fold 1 - Accuracy: 0.8825, Precision: 0.8863, Recall: 0.8825, F1-Score: 0.8821
Confusion Matrix:
[[1744  120]
 [ 307 1464]]

Fold 2
Total trainable parameters: 1,683,906


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Epoch 1/10, Loss: 0.3924
Epoch 2/10, Loss: 0.2251
Epoch 3/10, Loss: 0.1665
Epoch 4/10, Loss: 0.1297
Epoch 5/10, Loss: 0.0815
Epoch 6/10, Loss: 0.0771
Epoch 7/10, Loss: 0.0539
Epoch 8/10, Loss: 0.0746
Epoch 9/10, Loss: 0.0529
Epoch 10/10, Loss: 0.0325
Fold 2 - Accuracy: 0.8751, Precision: 0.8751, Recall: 0.8751, F1-Score: 0.8751
Confusion Matrix:
[[1618  216]
 [ 238 1563]]

Fold 3
Total trainable parameters: 1,683,906


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Epoch 1/10, Loss: 0.3868
Epoch 2/10, Loss: 0.2251
Epoch 3/10, Loss: 0.1677
Epoch 4/10, Loss: 0.1083
Epoch 5/10, Loss: 0.0781
Epoch 6/10, Loss: 0.0614
Epoch 7/10, Loss: 0.0600
Epoch 8/10, Loss: 0.0399
Epoch 9/10, Loss: 0.0457
Epoch 10/10, Loss: 0.0338
Fold 3 - Accuracy: 0.8957, Precision: 0.9006, Recall: 0.8957, F1-Score: 0.8955
Confusion Matrix:
[[1703   91]
 [ 288 1553]]


Final Results for MOBILENET:
Average Accuracy: 0.8845
Average Precision: 0.8874
Average Recall: 0.8845
Average F1-Score: 0.8842
Average Confusion Matrix:
[[1688.33333333  142.33333333]
 [ 277.66666667 1526.66666667]]
